
stages:
  - build
  - test
  - lint

build-frontend:
  stage: build
  image: node:16-alpine
  script:
    - cd frontend/
    - npm ci
    - npm run build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/frontend/node_modules/
    
frontend-linting-tests:
  stage: lint
  retry: 2
  needs:
    - job: build-frontend
  image: node:16-alpine
  script:
    - cd frontend/
    - node_modules/eslint/bin/eslint.js .

backend_linting_tests:
  stage: lint
  image: python:3.10
  before_script:
    - python -m pip install --upgrade pip
    - pip install black
  script:
    - cd backend
    - black . --check --verbose --color --extend-exclude="migrations|manage.py"

django-tests:
  stage: test
  image: python:3.10
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r backend/requirements.txt
    - pip install pytest-django
  script:
    - cd backend
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: backend/report.xml
    
    