image: python:3.10

stages:
  - test

before_script:
  - python -m pip install --upgrade pip
  - pip install -r backend/requirements.txt

test:
  stage: test
  script:
  - python backend/manage.py test